apiVersion: v1
kind: Pod
metadata:
  name: nettools
spec:
  containers:
  - name: nettools
    image: nicolaka/netshoot:latest # Or other suitable image like jedrecord/nettools
    command: ["bash", "-lc"]
    args:
      - sleep infinity
