# FlinkApplication.yaml
apiVersion: platform.confluent.io/v1beta1
kind: FlinkApplication
metadata:
  name: flink-app-shoes
  namespace: confluent
spec:
  flinkEnvironment: flink-env1
  image: venkyraghav941/flink-app-shoes:v3
  flinkVersion: v1_19
  # flinkConfiguration:
  #  taskmanager.numberOfTaskSlots: 2
  serviceAccount: flink
  jobManager:
    resource:
      memory: 1048m
      cpu: 1
  taskManager:
    resource:
      memory: 1048m
      cpu: 1
  job:
    jarURI: local:///opt/flink/shoes-app-0.1.jar
    state: running
    parallelism: 3
    upgradeMode: stateless
  cmfRestClassRef:
    name: default
    namespace: confluent