cmf:
  ssl:
    keystore: /opt/keystore/keystore.jks
    keystore-password: changeme
    trust-store: /opt/truststore/truststore.jks
    trust-store-password: changeme
    client-auth: need
  authentication:
    type: mtls
  authorization:
    mdsRestConfig:
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      authentication:
        type: oauth
        config:
          confluent.metadata.http.auth.credentials.provider: OAUTHBEARER
          confluent.metadata.oauthbearer.token.endpoint.url: http://keycloak:8080/realms/sso_test/protocol/openid-connect/token
          confluent.metadata.oauthbearer.login.client.id: ssologin
          confluent.metadata.oauthbearer.login.client.secret: KbLRih1HzjDC267PefuKU7QIoZ8hgHDK
          confluent.metadata.ssl.truststore.location: /opt/truststore/truststore.jks
          confluent.metadata.ssl.truststore.password: changeme
  k8s: #This configuration is only required if you did not setup FKO and CMF can reach FKO
    enabled: true
mountedVolumes:
  volumeMounts:
    - name: truststore
      mountPath: /opt/truststore
    - name: keystore
      mountPath: /opt/keystore
  volumes:
    - name: truststore
      configMap:
        name: cmf-truststore
    - name: keystore
      configMap:
        name: cmf-keystore