cmf:
  ssl:
    keystore: /opt/keystore/keystore.jks
    keystore-password: changeme
    trust-store: /opt/truststore/truststore.jks
    trust-store-password: changeme
    client-auth: need
  authentication:
    type: mtls
  k8s: #This configuration is only required if you did not setup FKO and CMF can reach FKO
    enabled: true
mountedVolumes:
  volumeMounts:
    - name: truststore
      mountPath: /opt/truststore
    - name: keystore
      mountPath: /opt/keystore
  volumes:
    - name: truststore
      configMap:
        name: cmf-truststore
    - name: keystore
      configMap:
        name: cmf-keystore